### PR TITLE
A11y fixes

### LINKED ISSUE #47: WCAG 1.4.3: Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds (.bg-blue-500.py-1.rounded-full)
#### Issue
`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))
#### Target application
[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)
#### Element path
.bg-blue-500.py-1.rounded-full
#### Snippet
`<span class="text-sm font-bold px-2 py-1 rounded-full text-white bg-blue-500">12</span>`
#### How to fix
    Fix any of the following:
      Element has insufficient color contrast of 3.7 (foreground color: #ffffff, background color: #2b7fff, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
#### Environment
Chrome version 140.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.46.0 (axe-core 4.10.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

### LINKED ISSUE #48: WCAG 1.4.3: Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds (.bg-green-500.py-1.rounded-full)
#### Issue

`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))

#### Target application

[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)

#### Element path

.bg-green-500.py-1.rounded-full

#### Snippet

`<span class="text-sm font-bold px-2 py-1 rounded-full text-white bg-green-500">19</span>`

#### How to fix

Fix any of the following:

Element has insufficient color contrast of 2.23 (foreground color: #ffffff, background color: #00c950, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1

#### Environment

Chrome version 140.0.0.0

This accessibility issue was found using Accessibility Insights for Web 2.46.0 (axe-core 4.10.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

### LINKED ISSUE #49: WCAG 1.4.3: Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds (.bg-purple-500.py-1.rounded-full)
#### Issue
`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))
#### Target application
[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)
#### Element path
.bg-purple-500.py-1.rounded-full
#### Snippet
`<span class="text-sm font-bold px-2 py-1 rounded-full text-white bg-purple-500">24</span>`
#### How to fix
    Fix any of the following:
      Element has insufficient color contrast of 4.04 (foreground color: #ffffff, background color: #ad46ff, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
#### Environment
Chrome version 140.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.46.0 (axe-core 4.10.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

### LINKED ISSUE #50: WCAG 1.4.3: Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds (.bg-pink-500)
#### Issue
`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))
#### Target application
[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)
#### Element path
.bg-pink-500
#### Snippet
`<span class="text-sm font-bold px-2 py-1 rounded-full text-white bg-pink-500">20</span>`
#### How to fix
    Fix any of the following:
      Element has insufficient color contrast of 3.58 (foreground color: #ffffff, background color: #f6339a, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
#### Environment
Chrome version 140.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.46.0 (axe-core 4.10.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

### LINKED ISSUE #51: WCAG 1.4.3: Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds (.bg-amber-500)
#### Issue
`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))
#### Target application
[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)
#### Element path
.bg-amber-500
#### Snippet
`<span class="text-sm font-bold px-2 py-1 rounded-full text-white bg-amber-500">20</span>`
#### How to fix
    Fix any of the following:
      Element has insufficient color contrast of 2.14 (foreground color: #ffffff, background color: #fe9a00, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
#### Environment
Chrome version 140.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.46.0 (axe-core 4.10.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

### LINKED ISSUE #52: WCAG 1.4.3: Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds (.bg-orange-500)
#### Issue
`Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))
#### Target application
[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)
#### Element path
.bg-orange-500
#### Snippet
`<span class="text-sm font-bold px-2 py-1 rounded-full text-white bg-orange-500">20</span>`
#### How to fix
    Fix any of the following:
      Element has insufficient color contrast of 2.82 (foreground color: #ffffff, background color: #ff6900, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
#### Environment
Chrome version 140.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.46.0 (axe-core 4.10.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

### LINKED ISSUE #53: Unclear button/link text of "here" on landing page
#### Issue

* `button` element used for text link
  * Ensure the correct element is being used for the purpose.
* Non-Descriptive Link/Button Text
  * Ensure link text is meaningful and descriptive, indicating the purpose or destination of the link.
  * Avoid using vague terms like “click here” or “read more.”
    * Example: Use “Download the annual report” instead of “Click here.”
* Lacks Contextual Clarity
  * The link/button text should make sense out of context. Users navigating via screen readers often jump from link to link or button to button.
    * Example: “Evaluate your project for all compliance requirements” provides clear context as link text when compared with just the word "here".

#### Target application

[AI Governance Dashboard](https://uscensusbureau.github.io/AI-Toolkit/pr-preview/pr-34/)

#### Element path

`#root > div > div.container.mx-auto.px-6.py-8.overflow-auto > div > section:nth-child(3) > div.bg-gradient-to-br.from-blue-50.to-purple-50.rounded-xl.p-6.mb-8.shadow-md > p > button`

#### Snippet

`<p class="text-lg text-gray-700 mb-4">You can also evaluate your project for all compliance requirements <button class="text-blue-600 hover:text-blue-800 underline font-medium cursor-pointer">here</button>.</p>`

#### How to fix

Include text that describes the destination within the link or button element so that it makes sense when viewed independently like a list of links in a screen reader.

#### More information

* [Section508.gov: Guide to Accessible Web Design & Development - Links and Buttons](https://www.section508.gov/develop/guide-accessible-web-design-development/#links_and_buttons)
* [Section508.gov: Accessibility Bytes No. 4: Descriptive Links and Hypertext](https://www.section508.gov/blog/accessibility-bytes/descriptive-links-and-hypertext/)
* [Eric Eggert: Buttons vs. Links](https://yatil.net/blog/buttons-vs-links)

### LINKED ISSUE #54: WCAG 1.4.3: Low contrast text: Heading/h3 text on landing page "Ready to Get Started?"
### Issue: 

Heading `h3` "Ready to Get Started?" has text set to white atop white background making that text invisible. 

### Screenshot:

With heading revealed and text selected: 

screenshot showing contrast problem

### Recommended fix:

* Ensure heading has a text style applied to ensure a 4.5:1 contrast ratio, or...
* Remove heading and text if not desired to be seen

### PR DESCRIPTION
**Pull request by rmartinez-xd**
Resolves the following accessibility issues: 

- resolves #54 - fixes low contrast text
- resolves #53 - fixes unclear button text/ call to action 
- resolves #52 - fixed contrasting background colors 
- resolves #51 - fixed contrasting background colors 
- resolves #50 - fixed contrasting background colors 
- resolves #49 - fixed contrasting background colors 
- resolves #48 - fixed contrasting background colors 
- resolves #47 - fixed contrasting background colors 

Changed icon color to #D7DAE0 and text to #000000 in "Available Assessment Modules" section

### CODE REVIEW

File: src/App.jsx [hunk 1]
```diff
@@ -587,7 +570,7 @@ const LandingPage = ({ onLaunchDashboard }) => {
             {/* Call to Action */}
             <div className="bg-gradient-to-br from-blue-600 to-purple-700 rounded-xl p-8 text-center shadow-xl">
               <div className="bg-white bg-opacity-10 rounded-xl p-6 backdrop-blur-sm">
-                <h3 className="text-2xl font-bold mb-3 text-white">Ready to Get Started?</h3>
+                <h3 className="text-2xl font-bold mb-3 ">Ready to Get Started?</h3>
```
Comment (curt-mitch-gov) [inline src/App.jsx]: We can remove this dangling white space in the className section:
```suggestion
                <h3 className="text-2xl font-bold mb-3">Ready to Get Started?</h3>
```

**Review by curt-mitch-gov — APPROVED** [review]
Left one minor comment, otherwise LGTM! :shipit:
